name: Node.js CI workflow

on:
  workflow_dispatch:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  ci:
    name: Deployment
    uses: merlusorg/GHA.workflows/.github/workflows/gha.workflows.build-node.yml@main